version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fast-feedback-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - fast-feedback-pgdata:/var/lib/postgresql/data

volumes:
  fast-feedback-pgdata: