name: Deployment

on:
  pull_request_target:
    types:
      - closed

jobs:
  deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: build and deploy application
        run: curl '${{ secrets.SERVER_URL }}/deploy?token=${{ secrets.TOKEN }}' -X 'POST'
